// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice = AnoukBruinSlice;

/**
 * Content for page documents
 */
interface PageDocumentData {
  /**
   * title field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * image field in *page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * github field in *page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.github
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  github: prismic.ImageField<never>;

  /**
   * facebook field in *page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.facebook
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  facebook: prismic.ImageField<never>;

  /**
   * email field in *page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  email: prismic.ImageField<never>;

  /**
   * instagram field in *page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.instagram
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  instagram: prismic.ImageField<never>;

  /**
   * bericht field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.bericht
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bericht: prismic.KeyTextField;

  /**
   * foto1 field in *page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.foto1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  foto1: prismic.ImageField<never>;

  /**
   * foto2 field in *page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.foto2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  foto2: prismic.ImageField<never>;

  /**
   * foto3 field in *page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.foto3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  foto3: prismic.ImageField<never>;

  /**
   * foto4 field in *page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.foto4
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  foto4: prismic.ImageField<never>;

  /**
   * foto5 field in *page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.foto5
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  foto5: prismic.ImageField<never>;

  /**
   * foto6 field in *page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.foto6
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  foto6: prismic.ImageField<never>;

  /**
   * foto7 field in *page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.foto7
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  foto7: prismic.ImageField<never>;

  /**
   * foto8 field in *page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.foto8
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  foto8: prismic.ImageField<never>;

  /**
   * foto9 field in *page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.foto9
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  foto9: prismic.ImageField<never>;

  /**
   * Slice Zone field in *page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>
  /**
   * Meta Description field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = PageDocument;

/**
 * Primary content in *AnoukBruin → Primary*
 */
export interface AnoukBruinSliceDefaultPrimary {
  /**
   * title field in *AnoukBruin → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: anouk_bruin.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for AnoukBruin Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AnoukBruinSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AnoukBruinSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AnoukBruin*
 */
type AnoukBruinSliceVariation = AnoukBruinSliceDefault;

/**
 * AnoukBruin Shared Slice
 *
 * - **API ID**: `anouk_bruin`
 * - **Description**: AnoukBruin
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AnoukBruinSlice = prismic.SharedSlice<
  "anouk_bruin",
  AnoukBruinSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AnoukBruinSlice,
      AnoukBruinSliceDefaultPrimary,
      AnoukBruinSliceVariation,
      AnoukBruinSliceDefault,
    };
  }
}
